# https://nixpacks.com/docs/configuration/file

providers = ['python', 'node'] # force python as the only provider, otherwise railway may think this is a node project

# set up some variables to minimize annoyance
[variables]
NIXPACKS_PYTHON_VERSION = '3.12'       # set python version to install
PIP_DISABLE_PIP_VERSION_CHECK = '1'    # the pip update notification is relatively useless in a production environment

[phases.setup]
nixPkgs = ['...', 'bun'] # add bun since it is needed to build the frontend

[phases.install]
cmds = [
  'curl -LsSf https://astral.sh/uv/install.sh | sh',
  'bun install --frozen-lockfile',
  'uv venv /opt/venv && . /opt/venv/bin/activate && uv sync --no-dev --frozen',
] # install uv, bun dependencies, and python packages

[start]
cmd = '/opt/venv/bin/app database upgrade --no-prompt && /opt/venv/bin/app run --wc 2 --host 0.0.0.0 --port $PORT'
