# https://nixpacks.com/docs/configuration/file

providers = ['python', 'node']

[variables]
NIXPACKS_PYTHON_VERSION = '3.12'
PIP_DISABLE_PIP_VERSION_CHECK = '1'

[phases.setup]
nixPkgs = ['...', 'bun']

[phases.install]
cmds = [
  'curl -LsSf https://astral.sh/uv/install.sh | sh',
  'export PATH="$HOME/.local/bin:$PATH"',
  'uv venv /opt/venv',
  '. /opt/venv/bin/activate && uv sync --no-dev --frozen',
]

[phases.build]
cmds = [
  'export PATH="$HOME/.local/bin:$PATH"',
  '. /opt/venv/bin/activate && uv run app assets install',
  '. /opt/venv/bin/activate && uv run app assets build',
]

[start]
cmd = '/opt/venv/bin/app database upgrade --no-prompt && /opt/venv/bin/app run --wc 2 --host 0.0.0.0 --port $PORT'
